name: cartouch
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  equatable: ^2.0.5
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  dotted_border: ^2.0.0+3
  dropdown_button2: ^1.9.2
  json_serializable: ^6.6.0
  sensors_plus: ^2.0.1
  flutter_switch: ^0.3.2
  hive_flutter: ^1.1.0
  logger: ^1.1.0
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  bloc_concurrency: ^0.2.0
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1
  flutter_modular: ^5.0.3
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.6
  bot_toast: ^4.0.3
  flutter_gen: ^5.0.3
  percent_indicator: ^4.2.2
  super_rich_text: ^1.0.0
  device_info_plus: ^8.1.0
  permission_handler: ^10.2.0
  image_downloader: ^0.31.0
  infinite_scroll_pagination: ^3.2.0
  mask_text_input_formatter: ^2.4.0
  loading_gifs: ^0.3.0
  http: ^0.13.5
  archive: ^3.3.6
  numeral: ^2.0.1
  file_picker: ^5.2.5
  gallery_saver: ^2.3.2
  shared_preferences: ^2.0.16
  shared_preferences_android: ^2.0.15
  animated_digit: ^3.2.1
  flutter_polyline_points: ^1.0.0
  data_table_2: ^2.3.8
  shimmer: ^2.0.0
  vibration: ^1.4.0
  simple_animations: ^4.2.0
  validators: ^3.0.0
  cupertino_icons: ^1.0.2
  vs_scrollbar: ^0.2.1
  camera: 0.10.2+1
  native_device_orientation: ^1.1.4
  flutter_launcher_icons: ^0.11.0
  smooth_page_indicator: ^1.0.1
  intl_phone_number_input: ^0.7.2
  pinput: ^2.2.31
  scroll_date_picker: ^3.6.1
  flutter_holo_date_picker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.2
  build_runner: ^2.3.2
  flutter_gen_runner:
  
flutter:
  uses-material-design: true
  assets:
    - assets/color/
    - assets/images/
    - assets/images/icons/
    - assets/images/views/
    - assets/langs/
#    - assets/pytorch_models/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf

flutter_gen:
  output: lib/core/utils/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  assets:
    enabled: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter_icons:
  image_path: "assets/images/cartouch_icon2.png"
  android: true
  ios: true
  remove_alpha_ios: true
